[package]
name = "native_rust_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.20"
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

[lib]
crate-type = ["staticlib", "cdylib"]